### ISSUE TITLE
Optional keys in JSON not recognizing unparsed fields

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1029]
I use the following config

```
LearnMode: False
AminerUser: 'aminer'
AminerGroup: 'aminer'

LogResourceList:
        - 'file:///home/ubuntu/data/log.txt'

Parser:

        - id: aaa
          type: FixedDataModelElement
          name: 'aaa'
          args: 'hello'

        - id: model
          start: True
          type: JsonModelElement
          name: 'parser'
          optional_key_prefix: '_'
          key_parser_dict:
            "_log": aaa
            "_stream": ALLOW_ALL

Input:
        json_format: True
        multi_source: False
        timestamp_paths: "/parser/timestamp"

Analysis:
        - type: 'NewMatchPathDetector'
          learn_mode: True

EventHandlers:
        - id: "stpe"
          json: true
          type: "StreamPrinterEventHandler"
```

to parse the following log file

```
{"log":"xyz","stream":"abc"}
```

I expect that the log line should be unparsed, because the "log" key exists but the value is "xyz" instead of "hello" as required by the FixedDataModelElement. However, the log event is parsed successfully and just not showing the path to the log key:

```
root@user-0:/home/ubuntu# aminer -C -c config.yml
{
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": 1,
    "AnalysisComponentType": "NewMatchPathDetector",
    "AnalysisComponentName": "NewMatchPathDetector1",
    "Message": "New path(es) detected",
    "PersistenceFileName": "Default",
    "TrainingMode": true,
    "AffectedLogAtomPaths": [
      "/parser"
    ],
    "ParsedLogAtom": {
      "/parser": "abc"
    }
  },
  "LogData": {
    "RawLogData": [
      "{\"log\":\"xyz\",\"stream\":\"abc\"}"
    ],
    "Timestamps": [
      1643269248.46
    ],
    "DetectionTimestamp": 1643269248.46,
    "LogLinesCount": 1,
    "AnnotatedMatchElement": "/parser: {'log': 'xyz', 'stream': 'abc'}\n  /parser: abc"
  }
}
```

This behavior is not intended and it also makes it really difficult to see that the parser does not actually fit the data as no unparsed event anomalies are returned. Please also add a test that checks that unparsed events are detected as such.
