### ISSUE TITLE
JsonParser: Enhance parser tree format with optional null value

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#1061]
Currently the log lines:
```
{„a“: null}
{„a“: {„b“: „b“}}
```

can be parser with the parser:
```
          - id: b
            type: FixedDataModelElement
            name: 'b'
            args: 'b'

          - id: n
            type: FixedDataModelElement
            name: 'n'
            args: 'null'

          - id: json
            type: JsonModelElement
            name: 'model'
            optional_key_prefix: '_'
            key_parser_dict:
              a:
                b: b

          - id: json2
            type: JsonModelElement
            name: 'model2'
            optional_key_prefix: '_'
            key_parser_dict:
              a: n

          - id: first
            start: True
            type: FirstMatchModelElement
            name: 'first'
            args:
              - json2
              - json
```

which is hard to read and could be enhanced.
