### ISSUE TITLE
ValueMatchRule: Bug related to bool values

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#1089]
An error occurs if the  yml-config
```
Parser:
        - id: a_list0
          type: FixedWordlistDataModelElement
          name: 'a_list0'
          args:
            - 'false'
            - 'true'

        - id: b_var0
          type: VariableByteDataModelElement
          name: 'b_var0'
          args: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.:"/@'

        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '_'
          key_parser_dict:
            a: a_list0
            b: b_var0


Input:
        timestamp_paths: [""]

Analysis:
        - type: 'NewMatchPathValueComboDetector'
          id: NCD
          paths:
            - '/model/a_list0'
            - '/model/b_var0'

        - type: 'AtomFilterMatchAction'
          id: AFMA
          subhandler_list:
            - NCD
          stop_when_handled_flag: True
          delete_components: True

        - type: 'ValueMatchRule'
          id: VMR
          path: "/model/a_list0"
          value: "true"
          match_action: AFMA

        - type: 'AllowlistViolationDetector'
          id: AVD
          allowlist_rules:
            - VMR
          suppress: True
```
is used to parse the line
```
{"a": true, "b": "a"}
```
