### ISSUE TITLE
Add possibility to run some LogResources as json input and some as normal text input.

### ISSUE THREAD

**Issue by ernstleierzopf** [ait-aecid/logdata-anomaly-miner#1155]
```
LogResourceList:

   - url: "file:///var/log/apache2/access.log"
   - url: "unix:///var/lib/akafka/aminer.sock"
     type: json  # Konfiguriert den ByteStream
     parser_id: kafka_audit_logs  # Konfiguriert den zugehörigen Parser


Parser:
   - id: kafka_audit_logs
     type: AuditDingsParser

   - id: ApacheAccessModel
     start: true
```
