### ISSUE TITLE
-o does not work properly with JsonModelElement

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#1158]
aminer should shutdown properly after finishing reading the logfile when executed with the parameter "-o". This doesn't seem to work with the following config:

```yaml
LearnMode: True

LogResourceList:
          - 'file:///logs/access.log'
            #          - 'file:///var/log/apache2/access.log'

Parser:
        - id: host
          type: VariableByteDataModelElement
          name: 'host'
          args: ' !"#$%&*=+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~'


        - id: user
          type: VariableByteDataModelElement
          name: 'user'
          args: ' !"#$%&*=+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]()^_`abcdefghijklmnopqrstuvwxyz{|}~'


        - id: method
          type: FixedWordlistDataModelElement
          name: 'method'
          args:
            - GET
            - PUT
            - POST
            - HEAD
            - DELETE
            - CONNECT
            - OPTIONS
            - TRACE
            - PATCH


        - id: path
          type: VariableByteDataModelElement
          name: 'path'
          args: ' !"#$%&*+=,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ}\[\\\]()^_`abcdefghijklmnopqrstuvwxyz{|}~'

        - id: size
          type: DecimalIntegerValueModelElement
          name: 'size'

        - id: code
          type: DecimalIntegerValueModelElement
          name: 'code'

        - id: referer
          type: VariableByteDataModelElement
          name: 'referer'
          args: ' !"#$%&*=+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~'


        - id: agent
          type: VariableByteDataModelElement
          name: 'agent'
          args: ' !"#$%&*=+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]()^_`abcdefghijklmnopqrstuvwxyz{|}~'


        - id: timestamp_model
          type: DateTimeModelElement
          name: 'timestamp'
          date_format: '%Y-%m-%dT%H:%M:%S+00:00'

        - id: 'START'
          start: True
          type: JsonModelElement
          name: accesslog
          optional_key_prefix: '_'
          nullable_key_prefix: '*'
          allow_all_fields: True
          key_parser_dict:
            "host": host
            "*user": user
            "method": method
            "path": path
            "size": size
            "code": code
            "*referer": referer
            "*agent": agent
            "time": timestamp_model

Input:
        json_format: True
        timestamp_paths: "/accesslog/timestamp"

Analysis:
        - type: "NewMatchPathValueDetector"
          paths: ["/accesslog/code"]
        - type: "NewMatchPathValueComboDetector"
          paths: ["/accesslog/method","/accesslog/path","/accesslog/agent"]

EventHandlers:
        - id: "stpe"
          type: "StreamPrinterEventHandler"
```

And with the following access.log: https://wolke.feedyourhead.at/s/LbSLxH95G6mgaKX

I tested the aminer with the following comand-line: "aminer -d 2 -C -c /etc/aminer/json-parser-config.yml -o"
