### ISSUE TITLE
FeatureRequest: ListModelElement

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#1173]
A ListModelElement could parse lists. It accepts a python list or a string in format '["one","two"]'.  The configuration file could look like:
```
parser:
 - id: agent
    type: VariableByteDataModelElement
    name: 'agent'
    args: ' !"#$%&*=+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]()^_`abcdefghijklmnopqrstuvwxyz{|}~'

  - type: ListModelElement
    id: lme
    key_parse_list:
      - index: 0
        model: agent
      - index: 1
        bypass: True 
```
