### ISSUE TITLE
Granular log resource list not working

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1225]
Using dicts in logresourcelist is not working. I tried to debug it and it seems that the reason for this is that in the aminer.py file and in the YamlConfig.py file, the following conversion is only done when the resource is a string, not a dict:

```
obj["url"] = decode_string_as_byte_string(resource)
```

This difference leads to type errors later on. Please also check why this has not occurred in the tests.

Config:
```
LearnMode: false

LogResourceList:
  - url: "file:///var/log/apache2/access.log"

Parser:
        - id: 'START'
          start: True
          type: ApacheAccessModel
          name: 'apache'

Input:
        timestamp_paths: "/accesslog/time"

Analysis:
        - type: "NewMatchPathValueDetector"
          paths: ["/accesslog/status"]
          output_logline: True

EventHandlers:
        - id: "stpe"
          type: "StreamPrinterEventHandler"
```

Error:
```
ubuntu@user:~$ sudo aminer -c /etc/aminer/config.yml -C
Traceback (most recent call last):
  File "/usr/bin/aminer", line 779, in <module>
    main()
  File "/usr/bin/aminer", line 519, in main
    if url.startswith(b'file://'):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```
