### ISSUE TITLE
AMiner instance identifier in anomaly output

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1241]
When multiple AMiner instances are running in an network and anomalies are centrally collected, it is not easy to identify to which server each anomaly belongs to. I suggest to introduce a new block "AMiner" in the anomaly output that has an "ID" that can be set in the config.yml. 

```
LearnMode: True
AMinerID: "mailserver-aminer"

LogResourceList:
        - 'file:///var/log/apache2/access.log'

Parser:
        - id: 'START'
          start: True
          type: ApacheAccessModel
          name: 'apache'

Input:
        timestamp_paths: "/accesslog/time"

Analysis:
        - type: "NewMatchPathValueDetector"
          paths: ["/accesslog/status"]
          output_logline: True

EventHandlers:
        - id: "stpe"
          type: "StreamPrinterEventHandler"
```

The output should look as follows:

```
{
  "AMiner": {
    "ID": "mailserver-aminer"
  },
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": 6,
    "AnalysisComponentType": "EntropyDetector",
    "AnalysisComponentName": "entropy_request",
    "Message": "Value entropy anomaly detected",
    "PersistenceFileName": "entropy_request",
    "TrainingMode": false,
    "AffectedLogAtomPaths": [
      "/model/fm/request/request"
    ],
    "AffectedLogAtomValues": [
      "/wp-content/uploads/2022/01/ekmkimzkps-1642996700.9285.php?wp_meta=WyIuL3dwaGFzaGNyYWNrLTAuMS93cGhhc2hjcmFjay5zaCIsICItdyIsICIkUFdEL3JvY2t5b3UudHh0IiwgIi1qIiwgIi4vd3BoYXNoY3JhY2stMC4xL2pvaG4tMS43LjYtanVtYm8tMTItTGludXg2NC9ydW4iLCAiLXUiLCAiamhhbGwiXQ%3D%3D"
    ],
    "CriticalValue": 0.03219069940839161,
    "ProbabilityThreshold": 0.05
  },
  "LogData": {
    "RawLogData": [
      "172.19.131.174 - - [24/Jan/2022:03:59:48 +0000] \"GET /wp-content/uploads/2022/01/ekmkimzkps-1642996700.9285.php?wp_meta=WyIuL3dwaGFzaGNyYWNrLTAuMS93cGhhc2hjcmFjay5zaCIsICItdyIsICIkUFdEL3JvY2t5b3UudHh0IiwgIi1qIiwgIi4vd3BoYXNoY3JhY2stMC4xL2pvaG4tMS43LjYtanVtYm8tMTItTGludXg2NC9ydW4iLCAiLXUiLCAiamhhbGwiXQ%3D%3D HTTP/1.1\" 200 506902 \"-\" \"python-requests/2.27.1\""
    ],
    "Timestamps": [
      1642996788
    ],
    "DetectionTimestamp": 1687185061,
    "LogLinesCount": 1
  }
}
```
