### ISSUE TITLE
PCA Detector parameter wrong documentation

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1290]
This is the sample configuration for the PCA detector in the documentation:

```
   - type: PCADetector
     id: PCADetector
     paths:
       - "/model/username"
       - "/model/service"
     windows_size: 60
     min_anomaly_score: 1.2
     min_variance: 0.95
     num_windows: 100
     learn_mode: true
```

However, it does not work since the parameter windows_size is actually called window_size. The documentation needs to be fixed.
