### ISSUE TITLE
Testcase for a parser-model without the "args" option

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#493]
Please create a test-case for a parser-model that has not arguments("args"):

```yaml
   Parser:                                                                                                                                                                     
        - id: 'apacheModel'                                                                                                                                                    
          type: ApacheAccessModel                                                                                                                                              
          name: 'apache'                                                                                                                                                       
                                                                                                                                                                               
        - id: 'startModel'                                                                                                                                                     
          start: True
          type: SequenceModelElement
          name: 'model'
          args: apacheModel
```
