### ISSUE TITLE
YamlConfig: The option "name" for "parser"-model must not be mandatory

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#494]
Currently we enforce to use the "name" option for the parser-model:

```yaml
   Parser:
        - id: 'apacheModel'
          type: ApacheAccessModel
          name: 'apache'

        - id: 'startModel'
          start: True
          type: SequenceModelElement
          name: 'model'
          args: apacheModel
```

This implies that we do not support parser that do not need an element-id, like the AnyByteDataModelElement(). Please fix this and write tests that proof that parsermodels like the AnyByteDataModelElement do also work with the yaml config
