### ISSUE TITLE
Parsing syslog from 29 Feb

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#521]
I think there is a problem with parsing logs from 29 Feb. The problem is that the aminer assumes that it is the current year, and parsing fails. Other dates seem to work. I know this sounds like an edge case, but our demonstration log data (https://zenodo.org/record/4264796) was recorded on this day, so I come across it quite often.

Sample logs:
```
Feb 29 00:09:01 mail-2 CRON[27153]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Feb 29 00:09:03 mail-2 systemd[1]: Starting Clean php session files...
```

Sample config:
```
LearnMode: True
AminerUser: 'aminer'
AminerGroup: 'aminer'

LogResourceList:
        - 'file:///home/ubuntu/sample.log'

Parser:
        - id: syslogModel
          type: SyslogParsingModel
          name: 'syslog'
          args: 'syslog'

        - id: model
          start: True
          type: SequenceModelElement
          name: 'parser'
          args: syslogModel

Input:
        verbose: True
        multi_source: False
        timestamp_paths: "/parser/model/time"


Analysis:
        - type: 'ParserCount'
          paths:
            - '/parser/model/host'
          report_interval: 5

EventHandlers:
        - id: "stpe"
          json: true
          type: "StreamPrinterEventHandler"
```

Output:
```
2021-03-08 11:14:10 Unparsed atom received
VerboseUnparsedAtomHandler: "None" (1 lines)
  {
  "DebugLog": [
    "Shortest unmatched data was b'Feb 29 00:09:01 mail-2 CRON[27153]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)'",
    ""
  ],
  "LogData": {
    "RawLogData": [
      "Feb 29 00:09:01 mail-2 CRON[27153]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)"
    ],
    "Timestamps": [
      1615202050.39
    ],
    "DetectionTimestamp": 1615202050.39,
    "LogLinesCount": 1
  },
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": null,
    "AnalysisComponentType": "VerboseUnparsedAtomHandler",
    "AnalysisComponentName": null,
    "Message": "Unparsed atom received",
    "PersistenceFileName": null
  }
}

2021-03-08 11:14:10 Unparsed atom received
VerboseUnparsedAtomHandler: "None" (1 lines)
  {
  "DebugLog": [
    "Shortest unmatched data was b'Feb 29 00:09:03 mail-2 systemd[1]: Starting Clean php session files...'",
    ""
  ],
  "LogData": {
    "RawLogData": [
      "Feb 29 00:09:03 mail-2 systemd[1]: Starting Clean php session files..."
    ],
    "Timestamps": [
      1615202050.39
    ],
    "DetectionTimestamp": 1615202050.39,
    "LogLinesCount": 1
  },
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": null,
    "AnalysisComponentType": "VerboseUnparsedAtomHandler",
    "AnalysisComponentName": null,
    "Message": "Unparsed atom received",
    "PersistenceFileName": null
  }
}
```
