### ISSUE TITLE
Improve config error output

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#628]
When something is not found in the config, the error output does not give any information where the error occurred. For example, when using an analyis component that does not exist, e.g.,

```
        - type: 'abc'
          paths:
            - '/parser/test'
          learn_mode: True
```

I would expect that "abc" shows up in the error, but it is just "{}":

```
root@user-5:/home/ubuntu# aminer -C -c /home/ubuntu/aminer/config.yml 
Config-Error: {'Analysis': [{1: ['none or more than one rule validate', {}]}]}
```

This should also be verified for other components such as output handlers, etc.
