### ISSUE TITLE
JsonError when multiple event handlers have json activated

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#629]
When multiple event handlers have json set to true, e.g.,

```
EventHandlers:
        - id: "stpe"
          json: true
          type: "StreamPrinterEventHandler"

        - id: "mqe"
          json: True
          topic: "raw_aminer"
          cfgfile: "/etc/aminer/kafka-client.conf"
          type: "KafkaEventHandler"
```

then the anomalies have the 

`"JsonError": "AnalysisComponent attribute \'AnalysisComponentIdentifier\' is already in use and can not be overwritten!\\nAnalysisComponent attribute \'AnalysisComponentType\' is already in use and can not be overwritten!\\nAnalysisComponent attribute \'AnalysisComponentName\' is already in use and can not be overwritten!\\nAnalysisComponent attribute \'Message\' is already in use and can not be overwritten!\\nAnalysisComponent attribute \'PersistenceFileName\' is already in use and can not be overwritten!\\n"`

appended, even though nothing should be wrong with this setup. I think this behavior comes from a bug in the YamlConfig.py, where the JsonConverterHandler is added multiple times to the pipeline.
