### ISSUE TITLE
Encoding in Json not working

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#740]
I have json logs that contain special characters (ä, ö, ü, ß, ...).

Logs:
```
{
  "host": "a ä z"
}
{
  "host": "a ä z"
}
```

Config:
```
LearnMode: True
AminerUser: 'aminer'
AminerGroup: 'aminer'
Log.Encoding: 'utf-8'

LogResourceList:
        - 'file:///home/ubuntu/gelf2.log'

Parser:
        - id: host_model
          type: FixedDataModelElement
          name: 'host'
          args: 'a ä z'

          #- id: model
          #start: True
          #type: SequenceModelElement
          #name: 'parser'
          #args:
          #  - host_model

        - id: model
          start: True
          type: JsonModelElement
          name: 'parser'
          key_parser_dict:
            "host": host_model

Input:
        verbose: True
        json_format: True
        multi_source: False
        timestamp_paths: "/parser/timestamp"


Analysis:
        - type: 'ParserCount'
          paths:
            - '/parser/version'
          report_interval: 5

EventHandlers:
        - id: "stpe"
          json: true
          type: "StreamPrinterEventHandler"
```

The logs cannot be parsed:
```
VerboseUnparsedAtomHandler: "None" (1 lines)
  {
  "DebugLog": [
    "Shortest unmatched data: \"{",
    "\"host\": \"a \u00e4 z\"",
    "}\"",
    ""
  ],
  "LogData": {
    "RawLogData": [
      "{\n  \"host\": \"a \u00e4 z\"\n}"
    ],
    "Timestamps": [
      1622642053.42
    ],
    "DetectionTimestamp": 1622642053.42,
    "LogLinesCount": 1
  },
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": null,
    "AnalysisComponentType": "VerboseUnparsedAtomHandler",
    "AnalysisComponentName": null,
    "Message": "Unparsed atom received",
    "PersistenceFileName": null
  }
}
```

I came to the conclusion that there is a problem in the json parsing element, since parsing non-json logs (see commented out sequencemodelelement) works with input data "a ä z".
