### ISSUE TITLE
Problem in JsonModelElement if all keys of an dictionary are optional

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#747]
Minimal example:

{"a": {}}

```
Parser:
        - id: a
          type: VariableByteDataModelElement
          name: 'a'
          args: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'

        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '+'
          key_parser_dict:
            a:
              +b: a
```

results in an error message.
