### ISSUE TITLE
output_event_handler parameter not working with json output

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#769]
I use the following log file:

```
ubuntu@user-5:~$ cat log.txt 
{"message": "asdf"}
```

and the following config:

```
ubuntu@user-5:~$ cat config.yml 
LearnMode: True
AminerUser: 'aminer'
AminerGroup: 'aminer'

LogResourceList:
        - 'file:///home/ubuntu/log.txt'

Parser:
        - id: message_model
          type: VariableByteDataModelElement
          name: 'message'
          args: ' =()!"#$%&*+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~'

        - id: model
          start: True
          type: JsonModelElement
          name: 'parser'
          optional_key_prefix: 'OPT_KEY_'
          key_parser_dict:
              "message": message_model

Input:
        verbose: True
        json_format: True
        multi_source: False
        timestamp_paths: "/parser/timestamp"


Analysis:
        - type: 'NewMatchPathValueDetector'
          paths:
            - '/parser/message'
          learn_mode: False
          output_event_handlers:
            - stpe

EventHandlers:
        - id: "stpe"
          json: false
          type: "StreamPrinterEventHandler"       

        - id: "stpe2"
          json: true
          type: "StreamPrinterEventHandler"
```

Note that stpe has json set to false and stpe2 has json set to true. When starting the aminer, I expect that the path detector sends an anomaly for the new path to both handlers, so that the anomaly is printed one time in json and one time in raw format. Moreover, the value detector should send an anomaly only to the stpe since this is set in the output_event_handlers parameter. The output is as expected:

```
ubuntu@user-5:~$ sudo aminer -C -c config.yml 
2021-06-25 06:44:00 New path(es) detected
NewMatchPathDetector: "DefaultNewMatchPathDetector" (1 lines)
  /parser: {'message': 'asdf'}
  /parser/message: asdf
['/parser', '/parser/message']
{"message": "asdf"}

2021-06-25 06:44:00 New path(es) detected
NewMatchPathDetector: "DefaultNewMatchPathDetector" (1 lines)
  {
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": 1,
    "AnalysisComponentType": "NewMatchPathDetector",
    "AnalysisComponentName": "DefaultNewMatchPathDetector",
    "Message": "New path(es) detected",
    "PersistenceFileName": "Default",
    "AffectedLogAtomPaths": [
      "/parser",
      "/parser/message"
    ],
    "ParsedLogAtom": {
      "/parser": {
        "message": "asdf"
      },
      "/parser/message": "asdf"
    }
  },
  "LogData": {
    "RawLogData": [
      "{\"message\": \"asdf\"}"
    ],
    "Timestamps": [
      1624603440.04
    ],
    "DetectionTimestamp": 1624603440.04,
    "LogLinesCount": 1,
    "AnnotatedMatchElement": "/parser: {'message': 'asdf'}\n  /parser/message: asdf"
  }
}

2021-06-25 06:44:00 New value(s) detected
NewMatchPathValueDetector: "NewMatchPathValueDetector2" (1 lines)
  /parser: {'message': 'asdf'}
  /parser/message: asdf
{'/parser/message': 'asdf'}
{"message": "asdf"}
```

When I change the json parameter to true in the stpe, I expect that the same anomalies are reported, but all are in json. New stpe:

```
        - id: "stpe"
          json: true
          type: "StreamPrinterEventHandler"
```

However, the output now only contains the path anomalies, not the value anomalies:

```
ubuntu@user-5:~$ sudo aminer -C -c config.yml 
2021-06-25 06:46:13 New path(es) detected
NewMatchPathDetector: "DefaultNewMatchPathDetector" (1 lines)
  {
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": 1,
    "AnalysisComponentType": "NewMatchPathDetector",
    "AnalysisComponentName": "DefaultNewMatchPathDetector",
    "Message": "New path(es) detected",
    "PersistenceFileName": "Default",
    "AffectedLogAtomPaths": [
      "/parser",
      "/parser/message"
    ],
    "ParsedLogAtom": {
      "/parser": {
        "message": "asdf"
      },
      "/parser/message": "asdf"
    }
  },
  "LogData": {
    "RawLogData": [
      "{\"message\": \"asdf\"}"
    ],
    "Timestamps": [
      1624603573.79
    ],
    "DetectionTimestamp": 1624603573.79,
    "LogLinesCount": 1,
    "AnnotatedMatchElement": "/parser: {'message': 'asdf'}\n  /parser/message: asdf"
  }
}

2021-06-25 06:46:13 New path(es) detected
NewMatchPathDetector: "DefaultNewMatchPathDetector" (1 lines)
  {
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": 1,
    "AnalysisComponentType": "NewMatchPathDetector",
    "AnalysisComponentName": "DefaultNewMatchPathDetector",
    "Message": "New path(es) detected",
    "PersistenceFileName": "Default",
    "AffectedLogAtomPaths": [
      "/parser",
      "/parser/message"
    ],
    "ParsedLogAtom": {
      "/parser": {
        "message": "asdf"
      },
      "/parser/message": "asdf"
    }
  },
  "LogData": {
    "RawLogData": [
      "{\"message\": \"asdf\"}"
    ],
    "Timestamps": [
      1624603573.79
    ],
    "DetectionTimestamp": 1624603573.79,
    "LogLinesCount": 1,
    "AnnotatedMatchElement": "/parser: {'message': 'asdf'}\n  /parser/message: asdf"
  }
}
```

I suspect that this is the case, because setting json to true adds an additional handler (JsonConverterHandler) and one of them is not correctly assigned the output_event_handler selection, therefore the anomaly is lost.
