### ISSUE TITLE
Escaped characters in variable byte element

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#777]
In some logs, certain characters are escaped with their encoded equivalent. For example, the following json log represents a dash:
`
{"a": "\x2d"}
`
I cannot find a way to parse this with a variable byte element. The following config shows some ideas (commented out), all of them result in unparsed atoms. At least one of them should work.

```
LearnMode: true
AminerUser: 'aminer'  # optional default: aminer
AminerGroup: 'aminer' # optional default: aminer

LogResourceList:
        - 'file:///home/ubuntu/file.log'

Parser:
        - id: a_key
          type: VariableByteDataModelElement
          name: 'a'
          #args: '-'
          #args: '\x2d'
          args: '\\x2d'

        - id: 'test'
          start: True
          type: JsonModelElement
          name: 'model'
          key_parser_dict: 
            a: a_key

Input:
        verbose: True # optional
        multi_source: False # optional
        timestamp_paths: "/model/accesslog/time"

Analysis:

EventHandlers:
        - id: "stpe"
          json: true # optional default: false
          type: "StreamPrinterEventHandler"
```
