### ISSUE TITLE
JsonModelElement: Problem with a floatelement in the last entry of the dictionary

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#778]
Minimal Example:

```
Parser:
        - id: a
          type: DecimalFloatValueModelElement
          name: 'a'

        - id: b
          type: DecimalFloatValueModelElement
          name: 'b'

        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '+'
          key_parser_dict:
            a: a
            b: b
```

Data:
{"a": 111.1, "b": 111.1}
{"a": 1E-1, "b": 111.1}
{"a": 111.1, "b": 1E-1}
{"a": 1E-1, "b": 1E-1}

The first two lines are parsed, but the second two not.
