### ISSUE TITLE
FixedWordlist not working with json in some situations

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#782]
This is my config file:

```
LearnMode: True

LogResourceList:
        - "file:///home/ubuntu/test.txt"

Parser:
       - id: d
         type: VariableByteDataModelElement
         name: 'd'
         args: '-.abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGGHIJKLMNOPQRSTUVWXYZ'

       - id: y
         type: FixedWordlistDataModelElement
         name: 'y'
         args:
           - 'abc'

       - id: json
         start: True
         type: JsonModelElement
         name: 'model'
         optional_key_prefix: 'OPT'
         key_parser_dict:
           "a":
             "OPTb":
               "OPTc":
                 "OPTd": d
             "OPTx":
               "OPTy": y

Input:
        timestamp_paths: None
        verbose: True
        json_format: True

EventHandlers:
        - id: stpe
          json: true
          type: StreamPrinterEventHandler
```

As expected, the parser is able to parse this input:

`
{"a": {"x": {"y": "abc"}}}
`

Output:

```
2021-07-12 07:13:30 New path(es) detected
NewMatchPathDetector: "DefaultNewMatchPathDetector" (1 lines)
  {
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": 1,
    "AnalysisComponentType": "NewMatchPathDetector",
    "AnalysisComponentName": "DefaultNewMatchPathDetector",
    "Message": "New path(es) detected",
    "PersistenceFileName": "Default",
    "AffectedLogAtomPaths": [
      "/model",
      "/model/a/x/y"
    ],
    "ParsedLogAtom": {
      "/model": {
        "a": {
          "x": {
            "y": "abc"
          }
        }
      },
      "/model/a/x/y": 0
    }
  },
  "LogData": {
    "RawLogData": [
      "{\"a\": {\"x\": {\"y\": \"abc\"}}}"
    ],
    "Timestamps": [
      1626074010.15
    ],
    "DetectionTimestamp": 1626074010.15,
    "LogLinesCount": 1,
    "AnnotatedMatchElement": "/model: {'a': {'x': {'y': 'abc'}}}\n  /model/a/x/y: 0"
  }
}
```

Which means that the FixedWordlist element is working. However, it is not possible to parse this input:

`
{"a": {"x": {"y": "abc"}, "b": {"c": {}}}}
`

Result:

```
2021-07-12 07:13:30 Unparsed atom received
VerboseUnparsedAtomHandler: "None" (1 lines)
  {
  "DebugLog": [
    "Starting match update on \"{\"a\": {\"x\": {\"y\": \"abc\"}, \"b\": {\"c\": {}}}}\"",
    "Removed: \"{\"a\": {\"x\": {\"y\": \"abc\", remaining 20 bytes",
    "Shortest unmatched data: \"\"}, \"b\": {\"c\": {}}}}\"",
    ""
  ],
  "LogData": {
    "RawLogData": [
      "{\"a\": {\"x\": {\"y\": \"abc\"}, \"b\": {\"c\": {}}}}"
    ],
    "Timestamps": [
      1626074010.15
    ],
    "DetectionTimestamp": 1626074010.15,
    "LogLinesCount": 1
  },
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": null,
    "AnalysisComponentType": "VerboseUnparsedAtomHandler",
    "AnalysisComponentName": null,
    "Message": "Unparsed atom received",
    "PersistenceFileName": null
  }
}
```

Only when the FixedWordlist is replaced with an ALLOW_ALL, i.e., 

```
       - id: json
         start: True
         type: JsonModelElement
         name: 'model'
         optional_key_prefix: 'OPT'
         key_parser_dict:
           "a":
             "OPTb":
               "OPTc":
                 "OPTd": d
             "OPTx":
               "OPTy": ALLOW_ALL #y
```

Then everything works again:

```
2021-07-12 07:37:45 New path(es) detected
NewMatchPathDetector: "DefaultNewMatchPathDetector" (1 lines)
  {
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": 1,
    "AnalysisComponentType": "NewMatchPathDetector",
    "AnalysisComponentName": "DefaultNewMatchPathDetector",
    "Message": "New path(es) detected",
    "PersistenceFileName": "Default",
    "AffectedLogAtomPaths": [
      "/model",
      "/model/a/x"
    ],
    "ParsedLogAtom": {
      "/model": {
        "a": {
          "x": {
            "y": "abc"
          },
          "b": {
            "c": {}
          }
        }
      },
      "/model/a/x": "abc"
    }
  },
  "LogData": {
    "RawLogData": [
      "{\"a\": {\"x\": {\"y\": \"abc\"}, \"b\": {\"c\": {}}}}"
    ],
    "Timestamps": [
      1626075465.54
    ],
    "DetectionTimestamp": 1626075465.54,
    "LogLinesCount": 1,
    "AnnotatedMatchElement": "/model: {'a': {'x': {'y': 'abc'}, 'b': {'c': {}}}}\n  /model/a/x: abc"
  }
}
```

This indicates that there is either a problem with the FixedWordlist element, empty objects, or a combination of both.
