### ISSUE TITLE
Check slashes in path names

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#796]
It is possible to use slashes in path names. For example, in the following config I map the "d" element to the same path as the "a/x" element.

```
LearnMode: True

LogResourceList:
        - "file:///home/ubuntu/testfile.txt"

Parser:

       - id: x
         type: VariableByteDataModelElement
         name: 'x'
         args: '.abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGGHIJKLMNOPQRSTUVWXYZ'

       - id: d
         type: VariableByteDataModelElement
         name: 'a/x'
         args: '-.abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGGHIJKLMNOPQRSTUVWXYZ'

       - id: json
         start: True
         type: JsonModelElement
         name: 'model'
         optional_key_prefix: 'OPT'
         key_parser_dict:
           "d": d
           "a":
               "x": x

Input:
        timestamp_paths: None
        verbose: True
        json_format: True

EventHandlers:
        - id: stpe
          json: true
          type: StreamPrinterEventHandler
```

I think in some places of the aminer code, these slashes are important, e.g., the ETD counts slashes in paths. Please add a test where a slash occur in a path and also where double slashes (e.g., "a//x") that correspond to empty path names are used and make sure that the aminer does not throw errors.
