### ISSUE TITLE
Add path detector and unparsed handler in analysis section

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#805]
When we introduced the yml config, we made the conscious decision to not include path detector and unparsed handler as own components, since these two detectors have to be included automatically anyway. However, user experience with yml config showed that it is relatively difficult to adjust parameters of these two detectors, which is necessary in some case. This especially concerns setting output_logline or suppress parameters, which have to be defined in the global space for these two detectors - this is not intuitive and it is not clear whether the settings apply to all analysis components.

I therefore propose the following solution. We add path and unparsed detectors as analysis components that can be defined in the analysis section of the yml config, where it is possible to set all parameters analogously to the other components. However, these two are optional, i.e., if they are not defined there, then they are still present with default parameters. In other words, defining these parameters in the config only overwrites the default parameter values. Of course, we have to remove the parameters for these detectors in the global space of the config.

**Comment by dITySoftware** [comment]
Currently there is no possibility to set output_logline for the DefaultNewMatchPathDetector. Also the suppress parameter is called suppress_unparsed and only affects the SimpleUnparsedAtomHandler or VerboseUnparsedAtomHandler.
The suppress_unparsed parameter is not global, it has to be defined in Input. I think the unparsed atom handlers belong to the input folder, as they do not analyse anything, but just output the wrong results.
There also is SuppressNewMatchPathDetector, which has to be defined globally.

The missing parameter for the output_logline.
For me it is clearer when the suppress_unparsed parameter has to be defined in Input.

My solution would be to define everything in Input. I would

- add yaml_data['Input']['DefaultNewMatchPathDetector.output_logline']
- rename yaml_data['SuppressNewMatchPathDetector'] to yaml_data['Input']['DefaultNewMatchPathDetector.suppress']

What do you think about it?

**Comment by 4cti0nfi9ure** [comment]
The feature described in the issue is a request from a PoC partner. Therefore, we should implement it.

**Comment by dITySoftware** [comment]
> The feature described in the issue is a request from a PoC partner. Therefore, we should implement it.

Yes, so I guess I will implement it in the way I described it?

**Comment by landauermax** [comment]
The path detector definitely belongs to the analysis section, it is an analysis component.

I know that the unparsed detector belongs to the input from an aminer point of view, but this is not clear for someone who uses the aminer, since the unparsed detector reports anomalies just as any other detector.

**Comment by dITySoftware** [comment]
Well how would you define it in the analysis section? And how should it be differentiable from the other analysis components?
In my opinion we should remove the DefaultNewMatchPathDetector as it makes more problems than it solves. It is hard to document and the users are probably better off adding it themselves.

Please give me a small example with one normal analysis component (for example value detector) and the unparsed and path detector. I will then change the code to work like that.

**Comment by landauermax** [comment]
```
LearnMode: True # optional

LogResourceList:
        - 'file:///var/log/apache2/access.log'

Parser:
        - id: 'START'
          start: True
          type: ApacheAccessModel
          name: 'apache'

Input:
        timestamp_paths: "/accesslog/time"

Analysis:
        - type: "NewMatchPathValueDetector"
          paths: ["/accesslog/status"]

        - type: "NewMatchPathDetector"
          output_logline: False
          learn_mode: False

EventHandlers:
        - id: "stpe"
          type: "StreamPrinterEventHandler"
```

**Comment by dITySoftware** [comment]
> ```
> LearnMode: True # optional
> 
> LogResourceList:
>         - 'file:///var/log/apache2/access.log'
> 
> Parser:
>         - id: 'START'
>           start: True
>           type: ApacheAccessModel
>           name: 'apache'
> 
> Input:
>         timestamp_paths: "/accesslog/time"
> 
> Analysis:
>         - type: "NewMatchPathValueDetector"
>           paths: ["/accesslog/status"]
> 
>         - type: "NewMatchPathDetector"
>           output_logline: False
>           learn_mode: False
> 
> EventHandlers:
>         - id: "stpe"
>           type: "StreamPrinterEventHandler"
> ```

Thanks. So the DefaultNewMatchPathDetector should not be added by default any more?
Please extend this config, to see how the VerboseUnparsedAtomHandler can be used and how the output of the unparsed handler can be suppressed (currently the option is in ['Input']['suppress_unparsed'])

Thanks :)

**Comment by landauermax** [comment]
No, as outlined in my first post in this issue, specifying these detectors is optional. Only when default parameters should be overwritten, it is necessary to do so.

With the unparsed I am not entirely sure what's the best option, since we could also make "verbose" a parameter. But in general, maybe something like this:

```
LearnMode: True # optional

LogResourceList:
        - 'file:///var/log/apache2/access.log'

Parser:
        - id: 'START'
          start: True
          type: ApacheAccessModel
          name: 'apache'

Input:
        timestamp_paths: "/accesslog/time"

Analysis:
        - type: "NewMatchPathValueDetector"
          paths: ["/accesslog/status"]

        - type: "NewMatchPathDetector"
          output_logline: False
          learn_mode: False

        - type: "VerboseUnparsedAtomHandler"
          suppress: True

EventHandlers:
        - id: "stpe"
          type: "StreamPrinterEventHandler"
```
