### ISSUE TITLE
Paths to JSON list elements

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#808]
I have this sample data:

```
root@user-5:/home/ubuntu# cat file3.log 
{"a": ["success", "a.png"]}
{"a": ["success", "b.png"]}
{"a": ["fail", "c.png"]}
{"a": ["success", "c.png"]}
```

The values in the list should be detected with a value detector. They should not be mixed, i.e., the first and second element in the list are independent.

I use the following config to parse the file:

```
LearnMode: True

LogResourceList:
  - "file:///home/ubuntu/file3.log"

Parser:  
       - id: x
         type: VariableByteDataModelElement
         name: 'x'
         args: '.abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGGHIJKLMNOPQRSTUVWXYZ'

       - id: json
         start: True
         type: JsonModelElement
         name: 'model'
         key_parser_dict:
           "a": 
             - x

Input:
        timestamp_paths: None
        verbose: True
        json_format: True

Analysis:
        - id: vd
          type: NewMatchPathValueDetector
          paths:
              - '/model/x'
          learn_mode: true
          persistence_id: test

EventHandlers:
        - id: stpe
          json: true
          type: StreamPrinterEventHandler
```

Note that I use a value detector on the list. The result is as follows:

```
root@user-5:/home/ubuntu# cat /var/lib/aminer/NewMatchPathValueDetector/test 
["bytes:a.png", "bytes:c.png", "bytes:b.png"]
```

Only the last value has been learned, but I also want to learn the first element in the array.

I propose to model all elements of the lists as their own elements, so that the parser looks like this:

```
Parser:
       - id: y
         type: FixedWordlistDataModelElement
         name: 'y'
         args:
           - 'success'
           - 'fail'
             
       - id: x
         type: VariableByteDataModelElement
         name: 'x'
         args: '.abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGGHIJKLMNOPQRSTUVWXYZ'

       - id: json
         start: True
         type: JsonModelElement
         name: 'model'
         key_parser_dict:
           "a": 
             - y
             - x
```

and the analysis could look like this, where each element can be addressed individually by an analysis component:

```
Analysis:
        - id: vd
          type: NewMatchPathValueDetector
          paths:
              - '/model/x'
          learn_mode: true
          persistence_id: test

        - id: vd
          type: NewMatchPathValueDetector
          paths:
              - '/model/y'
          learn_mode: true
          persistence_id: test
```

The current implementation uses a single element to model all elements of the list. This can also be convenient and should be possible by introducing a new element called ListOfElements. It should parse any number of elements in the list with the specified parsing model element. For example, the list of elements here is a list of variable byte elements:

```
Parser:
       - id: loe
         type: ListOfElements
         name: 'loe'
         args: z
             
       - id: z
         type: VariableByteDataModelElement
         name: 'z'
         args: '.abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGGHIJKLMNOPQRSTUVWXYZ'

       - id: json
         start: True
         type: JsonModelElement
         name: 'model'
         key_parser_dict:
           "a": 
             - loe
```

The ListOfElements element should then assign the index of the element in the JSON list at the end of the path. For example, the following paths can be used in the analysis section:

```
Analysis:
        - id: vd
          type: NewMatchPathValueDetector
          paths:
              - '/model/loe/0'
          learn_mode: true
          persistence_id: test

        - id: vd
          type: NewMatchPathValueDetector
          paths:
              - '/model/loe/1'
          learn_mode: true
          persistence_id: test
```

**Comment by dITySoftware** [comment]
The problem with the ListOfElements solution is that the values are overriden in the ParserMatch (see [here](https://github.com/ait-aecid/logdata-anomaly-miner/blob/development/source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/ParserMatch.py#L52)). So when the ListOfElements component checks for the paths with ParserMatch.get_match_dictionary(), it is already too late.

The best solution probably is to add these paths (/model/x/0 and /model/x/1) in the ParserMatch.get_match_dictionary method.

This would work, but the config would have to look like this for more values:
```
LearnMode: True

LogResourceList:
  - "file:///home/ubuntu/file3.log"

Parser:  
       - id: x
         type: VariableByteDataModelElement
         name: 'x'
         args: '.abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGGHIJKLMNOPQRSTUVWXYZ'

       - id: json
         start: True
         type: JsonModelElement
         name: 'model'
         key_parser_dict:
           "a": 
             - x

Input:
        timestamp_paths: None
        verbose: True
        json_format: True

Analysis:
        - id: vd
          type: NewMatchPathValueDetector
          paths:
              - '/model/x/0'
              - '/model/x/1'
              - '/model/x/2'
              - '/model/x/3'
              - '/model/x/4'
              - '/model/x/5'
              - '/model/x/6'
              - '/model/x/7'
              - '/model/x/8'
              - '/model/x/9'
              - '/model/x/10'
              - '/model/x/11'
              - '/model/x/12'
              - '/model/x/13'
              - '/model/x/14'
          learn_mode: true
          persistence_id: test

EventHandlers:
        - id: stpe
          json: true
          type: StreamPrinterEventHandler
```
Tbh, this is a really bad solution. Also the use case in which data structures are coded as list is not given in json. The data in this example probably would be coded as two json literals: status (= "success" or = "fail") and filename. Lists in json should also be handled as such. And the data type can be coded as DecimalIntegerValueModelElement for integers, DecimalFloatValueModelElement for floats, FixedWordlist for booleans or VariableByte for mixed data.

We should extend those analysers which are using values to check sub-paths, when the first match_dict.get() does not find the data. After changing the ParserMatch class, the match dictionary from the example looks like this:
`{'/model': <aminer.parsing.MatchElement.MatchElement object at 0x7f579cfa32b0>, '/model/x/0': <aminer.parsing.MatchElement.MatchElement object at 0x7f579cfad5e0>, '/model/x/1': <aminer.parsing.MatchElement.MatchElement object at 0x7f579cfad6a0>}`

My expected behavior would be that if I define
```
Analysis:
        - id: vd
          type: NewMatchPathValueDetector
          paths:
              - '/model/x'
          learn_mode: true
          persistence_id: test
```
all sub-paths of /model/x are checked, if /model/x is not found. But only if the sub-path is the last one (no children after that), it should be used. So for example /model/x/1 would be accepted, but /model/x/1/other not.

The original code of the NewMatchPathValueDetector looks like this:
```
for target_path in self.target_path_list:
            match = match_dict.get(target_path, None)
            if match is None:
                continue
```

An example implementation of the solution could be:
```
i = 0
        while i < len(self.target_path_list):
            target_path = self.target_path_list[i]
            match = match_dict.get(target_path, None)
            if match is None:
                added_path = False
                for key in match_dict.keys():
                    if key.startswith(target_path + "/") and "/" not in key.replace(target_path + "/", "", 1) and key not in self.target_path_list:
                        self.target_path_list = [key] + self.target_path_list
                        added_path = True
                        i = 0
                if not added_path:
                    i += 1
                continue
...
...
            i += 1
```

This works perfectly as the persisted data looks like this:
`["bytes:a.png", "bytes:c.png", "bytes:success", "bytes:fail", "bytes:b.png"]`

The solution is not very performant if the value actually does not match. Therefor I would introduce a new parameter called check_subpaths. The resulting code would have to look like this:
```
i = 0
        while i < len(self.target_path_list):
            target_path = self.target_path_list[i]
            match = match_dict.get(target_path, None)
            if match is None:
                added_path = True
                if self.check_subpath:
                    added_path = False
                    for key in match_dict.keys():
                        if key.startswith(target_path + "/") and "/" not in key.replace(target_path + "/", "", 1) and \
                                key not in self.target_path_list:
                            self.target_path_list = [key] + self.target_path_list
                            added_path = True
                            i = 0
                if not self.check_subpath or not added_path:
                    i += 1
                continue
...
...
            i += 1
```

**Comment by landauermax** [comment]
I do not think this solves the issue. As you say, the result would be that the AMiner learns

`["bytes:a.png", "bytes:c.png", "bytes:success", "bytes:fail", "bytes:b.png"]`

but I want to learn the state and file name with separate detectors, i.e.,

```
["bytes:success", "bytes:fail"]
["bytes:a.png", "bytes:c.png", "bytes:b.png"]
```

Also, I do not know how the data looks like for your example where the value detectors analyzes paths /model/x/0, ..., /model/x/14. Should all values of these paths be mixed together? Then yes, this is the solution that I would expect. 

Subpaths are really complicated and not performant.

**Comment by dITySoftware** [comment]
> I do not think this solves the issue. As you say, the result would be that the AMiner learns
> 
> `["bytes:a.png", "bytes:c.png", "bytes:success", "bytes:fail", "bytes:b.png"]`
> 
> but I want to learn the state and file name with separate detectors, i.e.,
> 
> ```
> ["bytes:success", "bytes:fail"]
> ["bytes:a.png", "bytes:c.png", "bytes:b.png"]
> ```
> 
> Also, I do not know how the data looks like for your example where the value detectors analyzes paths /model/x/0, ..., /model/x/14. Should all values of these paths be mixed together? Then yes, this is the solution that I would expect.
> 
> Subpaths are really complicated and not performant.

Well this should work as well. Just use following config:
```
Analysis:
        - id: vd1
          type: NewMatchPathValueDetector
          paths:
              - '/model/x/0'
          learn_mode: true
          persistence_id: test

        - id: vd2
          type: NewMatchPathValueDetector
          paths:
              - '/model/x/1'
          learn_mode: true
          persistence_id: test2
```

Are you really sure json arrays are used in your proposed way?
I have never seen json arrays being used as data structures like this, but rather as a real array - with one type of values or multiple ones.
