### ISSUE TITLE
Feature: Support for YAML-Format for ParserModels

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#884]
It is currently possible to configure ParserModels in config.yml but this file gets very big with more complex ParserModels. A solution is to write ParserModels in python and place them into conf-enabled. Aminer should also allow to place ParserModels in YAML-format in conf-enabled and check the schema for those models.

**Comment by dITySoftware** [comment]
This functionality is already working, because you can use these models within the yaml config. Here is an example:
```
Parser:
        - id: apache
          type: ApacheAccessModel
          name: 'apache'
          start: True
```
If I create a copy of the model with a new name (`cp /etc/aminer/conf-enabled/ApacheAccessModel.py /etc/aminer/conf-enabled/ApacheAccessModelNew.py`), it is still working. 

Second config:
```
Parser:
        - id: apache
          type: ApacheAccessModelNew
          name: 'apache'
          start: True
```

It works because of this code in the `ConfigValidator`:
```
        if name.endswith("ModelElement"):
            self.is_model = True
            # Classes must be imported from the right modules. Some class names do not match the module name and need to be set explicitly.
            module = "aminer.parsing"
            if name == "DebugMatchContext":
                module += ".MatchContext"
            if name == "MultiLocaleDateTimeModelElement":
                module += ".DateTimeModelElement"
            else:
                module += "." + name
            self.func = getattr(__import__(module, fromlist=[name]), name)
        else:
            self.is_model = False
            # we need this import:
            # skipcq: PTC-W0034
            self.func = getattr(__import__(name), "get_model")
```

Please reopen this issue if functionality is missing.
