### ISSUE TITLE
allow_all_fields param not working

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#891]
Sample log:

```
{
  "aa": "a1",
  "fields": {
    "bb": "b1",
    "cc": [
      "c1"
    ],
    "dd": "d1"
  }
}
```

Sample config:

```
LearnMode: True

LogResourceList:
  - "file:///home/ubuntu/mizi.log"

Parser:
       - id: b
         type: VariableByteDataModelElement
         name: 'b'
         args: '.abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGGHIJKLMNOPQRSTUVWXYZ'

       - id: json
         start: True
         type: JsonModelElement
         name: 'model'
         allow_all_fields: True
         key_parser_dict:
           fields:
             "bb": b

Input:
        timestamp_paths: None
        verbose: True
        json_format: True

EventHandlers:
        - id: stpe
          json: true
          type: StreamPrinterEventHandler
```

The fields.bb field is present in the logs, and the allow_all_fields parameter is set to True, therefore the input log should be parsed since all other fields in the sample log should be skipped in this case. However, the log is unparsed:

```
{
  "DebugLog": [
    "Starting match update on \"{",
    "\"aa\": \"a1\",",
    "\"fields\": {",
    "\"bb\": \"b1\",",
    "\"cc\": [",
    "\"c1\"",
    "],",
    "\"dd\": \"d1\"",
    "}",
    "}\"",
    "Removed: \"{",
    "\"\", remaining 91 bytes",
    "Shortest unmatched data: \"aa\": \"a1\",",
    "\"fields\": {",
    "\"bb\": \"b1\",",
    "\"cc\": [",
    "\"c1\"",
    "],",
    "\"dd\": \"d1\"",
    "}",
    "}\"",
    ""
  ],
  "LogData": {
    "RawLogData": [
      "{\n  \"aa\": \"a1\",\n  \"fields\": {\n    \"bb\": \"b1\",\n    \"cc\": [\n      \"c1\"\n    ],\n    \"dd\": \"d1\"\n  }\n}"
    ],
    "Timestamps": [
      1628504183.19
    ],
    "DetectionTimestamp": 1628504183.19,
    "LogLinesCount": 1
  },
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": null,
    "AnalysisComponentType": "VerboseUnparsedAtomHandler",
    "AnalysisComponentName": null,
    "Message": "Unparsed atom received",
    "PersistenceFileName": null
  }
}
```
