### ISSUE TITLE
JsonModelElement: Dictionaries in lists

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#925]
Log line
```
{"a1":[{"a2": "b", "a3": "b"}, {"a4": "b", "a5": "b"}]}
```

is currently parsed with the parser

```
Parser: 
        - id: a_var1
          type: VariableByteDataModelElement
          name: 'a_var1'
          args: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"
 
        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '_'
          key_parser_dict:
            a1:
              - _a2: a_var1
                _a3: a_var1
                _a4: a_var1
                _a5: a_var1
```

but should be parsed with the following parser.

```
Parser: 
        - id: a_var1
          type: VariableByteDataModelElement
          name: 'a_var1'
          args: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"
 
        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '_'
          key_parser_dict:
            a1:
              - _a2: a_var1
                _a3: a_var1
              - _a4: a_var1
                _a5: a_var1
```
