### ISSUE TITLE
JsonModelElement: Bug with ALLOW_ALL

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#947]
Log line
```
{"a1": "b"}
```
can be parser with the parser
```
Parser: 
        - id: a_var1
          type: VariableByteDataModelElement
          name: 'a_var1'
          args: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"
 
        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '_'
          key_parser_dict:
            a1: a_var1
```
but not
```
Parser: 
        - id: a_var1
          type: VariableByteDataModelElement
          name: 'a_var1'
          args: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"
 
        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '_'
          key_parser_dict:
            a1: ALLOW_ALL
```
