### ISSUE TITLE
Problem in processing order of log lines

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#961]
Log lines are processed in a false order when using multi_source: False (and probably json-parser). Expected procession order are all log lines of the first file followed by the lines of the second file.

Order of procession of lines to the files is 1...1 2...2 1...1

Config:
```
LearnMode: True
AminerUser: 'aminer'
AminerGroup: 'aminer'

LogResourceList:
        - 'file:///file1.log'
        - 'file:///file2.log'

Parser:
        - id: tags_str0
          type: FixedDataModelElement
          name: 'tags_str0'
          args: "beats_input_codec_plain_applied"

        - id: message_var0
          type: VariableByteDataModelElement
          name: 'message_var0'
          args: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_ ,.;:='/+[()]"

        - id: dataset_str0
          type: FixedDataModelElement
          name: 'dataset_str0'
          args: 'system.auth'

        - id: timezone_str0
          type: FixedDataModelElement
          name: 'timezone_str0'
          args: '+00:00'

        - id: module_str0
          type: FixedDataModelElement
          name: 'module_str0'
          args: 'system'

        - id: path_var0
          type: VariableByteDataModelElement
          name: 'path_var0'
          args: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_./"

        - id: offset_int
          type: DecimalIntegerValueModelElement
          name: 'offset_int'

        - id: version_str0
          type: FixedDataModelElement
          name: 'version_str0'
          args: '1'

        - id: name_str0
          type: FixedDataModelElement
          name: 'name_str0'
          args: 'auth'

        - id: timestamp_time0
          type: DateTimeModelElement
          name: 'timestamp_time0'
          date_format: '%Y-%m-%dT%H:%M:%S.%fZ'

        - id: name_str1
          type: FixedDataModelElement
          name: 'name_str1'
          args: 'intranet-server'

        - id: version_str1
          type: FixedDataModelElement
          name: 'version_str1'
          args: '1.9.0'

        - id: type_str0
          type: FixedDataModelElement
          name: 'type_str0'
          args: 'log'

        - id: type_str1
          type: FixedDataModelElement
          name: 'type_str1'
          args: 'filebeat'

        - id: version_str2
          type: FixedDataModelElement
          name: 'version_str2'
          args: '7.13.2'

        - id: hostname_str0
          type: FixedDataModelElement
          name: 'hostname_str0'
          args: 'intranet-server'

        - id: ephemeral_id_var0
          type: VariableByteDataModelElement
          name: 'ephemeral_id_var0'
          args: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"

        - id: id_str0
          type: FixedDataModelElement
          name: 'id_str0'
          args: '332dbe89-8f21-4049-bfe3-1e908265530e'

        - id: type_str2
          type: FixedDataModelElement
          name: 'type_str2'
          args: 'system'

        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '_'
          key_parser_dict:
            tags:
              - tags_str0
            message: message_var0
            event:
              dataset: dataset_str0
              timezone: timezone_str0
              module: module_str0
            log:
              file:
                path: path_var0
              offset: offset_int
            "@version": version_str0
            fileset:
              name: name_str0
            "@timestamp": timestamp_time0
            host:
              name: name_str1
            ecs:
              version: version_str1
            input:
              type: type_str0
            agent:
              type: type_str1
              name: name_str1
              version: version_str2
              hostname: hostname_str0
              ephemeral_id: ephemeral_id_var0
              id: id_str0
            service:
              type: type_str2

Input:
        verbose: True
        multi_source: False
        json_format: True
        timestamp_paths:
          - '/model/timestamp_time0'

Analysis:
        - type: 'ParserCount'
          paths:
            - '/model'
          report_interval: 5

        - type: 'EventTypeDetector'
          id: ETD

EventHandlers:
        - id: "stpe"
          type: "StreamPrinterEventHandler"
```
[file1.log](https://github.com/ait-aecid/logdata-anomaly-miner/files/7225867/file1.log)
[file2.log](https://github.com/ait-aecid/logdata-anomaly-miner/files/7225868/file2.log)
